stages:
  - validate

validateConfig:
  stage: validate
  image: node:latest
  tags:
    - docker-runner
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 days
    when: always
  script:
    - npm --version
    - npm i -g renovate
    - RENOVATE_CONFIG_FILE=default.json renovate-config-validator
  cache:
    key: cache-over-all-branches-npm
    paths:
      - .npm/
      - node_modules/
